### ISSUE TITLE
click doesn't get installed automatically when installing visma via pip

### ISSUE THREAD

**Issue by sniku** [pwitab/visma#15]
`click` doesn't get installed automatically when installing `visma` via pip.

```
(venv) root@homedesktop:/home/sniku/workspace/teklager/teklager_se# visma 
Traceback (most recent call last):
  File "/home/sniku/workspace/teklager/teklager_se/venv/bin/visma", line 7, in <module>
    from visma.cli import cli
  File "/home/sniku/workspace/teklager/teklager_se/venv/lib/python3.6/site-packages/visma/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```
After installing `click` everything works correctly.

```
(venv) root@homedesktop:/home/sniku/workspace/teklager/teklager_se# pip install click
Collecting click
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 3.0MB/s 
Installing collected packages: click
Successfully installed click-7.0
(venv) root@homedesktop:/home/sniku/workspace/teklager/teklager_se# visma 
Usage: visma [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  get-token
  request-access
```

**Comment by Krolken** [comment]
This if my bad. I should have looked into if it installed properly.
I will make the setup.py better so everything will install nicely.
